disabled = false
languageCode = "en"
languageName = "English"
weight = 20
title = "Served Smart - Joinery (Example website)"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "02 January 2006"
# logo = "/img/logo-optimized.svg"
# secondaryLogo = "/img/secondary-logo.png"
description = "Any work with wood is our specialty. We specialize in joinery, repairs, modifications, and furniture manufacturing!"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Served Smart - Joinery (Example website)"
email = "info@servedsmart.com"
image = "/img/author-512x512.png"
imageQuality = 96
headline = "Joinery with many years of experience and friendly and well-trained staff"
bio = "We enjoy restoring old furniture and making/installing custom doors/window frames etc."
links = [
 { email = "mailto:info@servedsmart.com" },
 #     { link = "https://link-to-some-website.com/" },
 #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
 #     { apple = "https://www.apple.com" },
 #     { blogger = "https://username.blogspot.com/" },
 #     { bluesky = "https://bsky.app/profile/username" },
 #     { codepen = "https://codepen.io/username" },
 #     { dev = "https://dev.to/username" },
 #     { discord = "https://discord.gg/invitecode" },
 #     { dribbble = "https://dribbble.com/username" },
 #     { facebook = "https://facebook.com/username" },
 #     { flickr = "https://www.flickr.com/photos/username/" },
 #     { foursquare = "https://foursquare.com/username" },
 { github = "https://github.com/servedsmart" },
 #     { gitlab = "https://gitlab.com/username" },
 #     { google = "https://www.google.com/" },
 #     { hashnode = "https://username.hashnode.dev" },
 #     { instagram = "https://instagram.com/username" },
 #     { itch-io = "https://username.itch.io" },
 #     { keybase = "https://keybase.io/username" },
 #     { kickstarter = "https://www.kickstarter.com/profile/username" },
 #     { lastfm = "https://lastfm.com/user/username" },
 #     { linkedin = "https://linkedin.com/in/username" },
 #     { mastodon = "https://mastodon.instance/@username" },
 #     { medium = "https://medium.com/username" },
 #     { microsoft = "https://www.microsoft.com/" },
 #     { orcid = "https://orcid.org/userid" },
 #     { patreon = "https://www.patreon.com/username" },
 #     { pinterest = "https://pinterest.com/username" },
 #     { reddit = "https://reddit.com/user/username" },
 #     { researchgate = "https://www.researchgate.net/profile/username" },
 #     { slack = "https://workspace.url/team/userid" },
 #     { snapchat = "https://snapchat.com/add/username" },
 #     { soundcloud = "https://soundcloud.com/username" },
 #     { spotify = "https://open.spotify.com/user/userid" },
 #     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
 #     { steam = "https://steamcommunity.com/profiles/userid" },
 #     { telegram = "https://t.me/username" },
 #     { threads = "https://www.threads.net/@username" },
 #     { tiktok = "https://tiktok.com/@username" },
 #     { tumblr = "https://username.tumblr.com" },
 #     { twitch = "https://twitch.tv/username" },
 #     { twitter = "https://twitter.com/username" },
 #     { x-twitter = "https://twitter.com/username" },
 #     { whatsapp = "https://wa.me/phone-number" },
 #     { youtube = "https://youtube.com/username" },
 #     { ko-fi = "https://ko-fi.com/username" },
 #     { codeberg = "https://codeberg.org/username"},
]

# Custom
[[params.consent.items]]
title = "Appearance"
description = "This code allows users to modify the website appearance."
descriptionSummary = "The data 'appearance' will be saved to localStorage."
isFunctional = false
scriptFile = "js/consent-appearance.js"

[[params.consent.items]]
title = "Consent Settings"
description = "This data allows us to read a user's consent settings."
descriptionSummary = "The data 'optional-script-hashes' and 'consent-settings' will be saved to localStorage."
isFunctional = true
