name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: cloudflare-access
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Dependencies - npm
        run: npm ci

      - name: Build Hugo Site
        run: npm run-script build

      - name: Install Dependencies - yq
        if: github.ref == 'refs/heads/main'
        run: pip install yq

      - name: Install Dependencies - pup
        if: github.ref == 'refs/heads/main'
        uses: actions/setup-go@v5
        with:
          go-version: "^1.24.4"
        run: go install github.com/servedsmart/pup@1.0.0

      - name: Deploy via API
        if: github.ref == 'refs/heads/main'
        env:
          CLOUDFLARE_API_TOKEN_1: ${{ secrets.CLOUDFLARE_API_TOKEN_1 }}
          CLOUDFLARE_ZONE_ID_0: ${{ secrets.CLOUDFLARE_ZONE_ID_0 }}
          JSON_SECRETS: ${{ toJson(secrets) }}
        run: ./.github/scripts/deploy-cloudflare-api.sh

      - name: Deploy to Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_0 }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npm run-script deploy
